name: CD - Build & Push Docker Image & Helm Chart

on:
  push:
    branches:
      - dev
      - stage
      - main
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: usm-app
  HELM_REGISTRY: 879381282588.dkr.ecr.us-east-1.amazonaws.com/helm
  CHART_PATH: charts/usm-app
  IMAGE_TAG: v0.1.${{ github.run_number }}

permissions:
  id-token: write
  contents: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::879381282588:role/internal-dev-github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${IMAGE_TAG}

      - name: Update Helm values.yaml with new image tag
        run: sed -i "s/tag: \".*\"/tag: \"${IMAGE_TAG}\"/" $CHART_PATH/values.yaml

      - name: Set u
